[package]
name = "ddql"
version = "0.1.0"
authors = ["Cheung Chifung <chifung.cheung@gmail.com>"]

[dependencies]
nom = "^4.0"
base64 = "0.9.2"
clap = "2.32"
lazy_static = "1.1.0"
rusoto_core = "0.32.0"
rusoto_dynamodb = "0.32.0"
prettytable-rs = "^0.7"